replicaCount: 1

image:
  repository: ghcr.io/rso-2024-group-12/microservice-skladisce
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8082

probes:
  liveness:
    enabled: true
    path: /q/health/live
  readiness:
    enabled: true
    path: /q/health/ready

config:
  kafka:
    bootstrapServers: "nakupify-kafka-kafka-bootstrap.default.svc.cluster.local:9092"
  postgres:
    username: "nakupify"
    password: "nakupify"
    jdbcUrl: "jdbc:postgresql://nakupify-db-rw.default.svc.cluster.local:5432/nakupify"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"